version: '3'
services:
  influxdb:
    image: influxdb:2.7
    volumes:
      - /mnt/storage/stats/influxdbv2:/var/lib/influxdb2:rw
      # - ./ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt:rw
      # - ./ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key:rw
    # ports:
    #   - "8086:8086"
    networks:
      - stats 
      - web
    env_file:
      - ./influxv2.env
    restart: unless-stopped
    labels:
      - traefik.http.routers.influx.entryPoints=web-secure
      - traefik.http.routers.influx.rule=Host(`influx.federation.home`)
      - traefik.http.routers.influx.tls=true
      - traefik.http.services.influx.loadbalancer.server.port=8086

  # Use the influx cli to set up an influxdb instance. 
  influxdb_cli:
    image: influxdb:2.6
    networks: 
      - stats
    profiles:
      - setup
    env_file: 
      - ./influxv2.env
    entrypoint: ["./entrypoint.sh"]
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:latest
    volumes: 
      - grafana-storage:/var/lib/grafana
    networks:
      - stats
      - web
    env_file: 
      - ./grafana.env
    depends_on: 
      - influxdb
      - grafana-renderer
    restart: unless-stopped
    labels:
      - traefik.http.routers.grafana.entryPoints=web-secure
      - traefik.http.routers.grafana.rule=Host(`grafana.federation.home`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000

  grafana-renderer:
    image: grafana/grafana-image-renderer:latest
    networks: 
      - stats
    restart: unless-stopped

volumes: 
  grafana-storage:

networks: 
  stats:
  web:
    external: true
